spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:dpg-cr6mr25ds78s73c0bjbg-a}:${DB_PORT:5432}/${DB_NAME:postgresql_hellophp_mwe8}
    # url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scraping}
    # url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:scraping}
    username: ${DB_USER:postgresql_hellophp_mwe8_user}
    # username: ${DB_USER:postgres}
    password: ${DB_PASS:NhCR2E5qyTAVtQDa0cMgoR9WZXgXby1R}
    # password: ${DB_PASS:postgres}
  mail:
    host: ${MAIL_HOST:scraping-mailpit}
    # host: ${MAIL_HOST:localhost}
    # host: ${MAIL_HOST:mail}
    port: ${MAIL_PORT:1025}
  batch:
    jdbc:
      initialize-schema: always
